package com.woniu.pojo;
// Generated 2019-11-25 11:05:09 by Hibernate Tools 5.1.10.Final

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private int deptno;
	private String deptname;

	public Dept() {
	}

	public Dept(int deptno) {
		this.deptno = deptno;
	}

	public Dept(int deptno, String deptname) {
		this.deptno = deptno;
		this.deptname = deptname;
	}

	public int getDeptno() {
		return this.deptno;
	}

	public void setDeptno(int deptno) {
		this.deptno = deptno;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	@Override
	public String toString() {
		return "Dept [deptno=" + deptno + ", deptname=" + deptname + "]";
	}

}
